### ISSUE TITLE
Problem to treat this repository as vendor

### ISSUE THREAD

**Issue by miroslavKovacPantheon** [FujitsuNetworkCommunications/FSS2-Yang#1]
Hi Fujitsu network communications,

First thank you for contributing in yangModels/yang and subsequently in yangcatalog as well. 

This repository is fine as it is and we don t have problems to parse modules inside of it. But there is a automated job for this that works with platform-metadata.json files and hello-message.xml from your device. If you look for example [here](https://github.com/YangModels/yang/tree/master/vendor/cisco/xe/16111) there are several hello-message.xml files named like [capability-ir1101.xml](https://github.com/YangModels/yang/blob/master/vendor/cisco/xe/16111/capability-ir1101.xml), [capability-cat9600.xml](https://github.com/YangModels/yang/blob/master/vendor/cisco/xe/16111/capability-cat9600.xml) and so on.....  these files are all mentioned in [platform-metadata.json](https://github.com/YangModels/yang/blob/master/vendor/cisco/xe/16111/platform-metadata.json) file with vendor name software version os-type and so on. This way it will be easy to search for your modules using yangcatalog.

Would this be something that you could add here in matter of days?

**Comment by bclaise** [comment]
Alternatively, you can contact us via email to solve this issue:  info@yangcatalog.org

**Comment by karanmarjara** [comment]
@miroslavKovacPantheon  and @bclaise  thank you for raising this issue. We are looking into this.

@bennfnc Can you please look into this and give me an update.  Thanks.

**Comment by bclaise** [comment]
Miroslav, can we load the YANG modules in the mean time?

**Comment by bennfnc** [comment]
Hello @bclaise, @miroslavKovacPantheon,
We can arrange for the capabilities.xml files for the yang models we have published. 

However, we wanted to know more about the metadata.json file. Is there a standard format for the metadata.json file? What is the recommended structure/schema for this file? Is there a standard schema/structure for this metadata.json file that we need to follow?

Regards,
Suraj.

**Comment by miroslavKovacPantheon** [comment]
Hi,

yes there is. it has to follow nodes of [this](https://github.com/YangCatalog/deployment/blob/master/confd/platform-implementation-metadata.yang) yang file.

you can look at examples of cisco metadata.json files for example [this one](https://github.com/YangModels/yang/blob/master/vendor/cisco/xr/612/platform-metadata.json) or [this one](https://github.com/YangModels/yang/blob/master/vendor/cisco/xr/662/platform-metadata.json)

I can review it if you want me to before submitting just let me know

regards,
Miroslav Kovac

**Comment by bennfnc** [comment]
I have added the required capabilities and platform-metadata files. Please let me know if this works. Closing this issue for now. Happy holidays!!
