### ISSUE TITLE
platform-metada.json file issues

### ISSUE THREAD

**Issue by miroslavKovacPantheon** [FujitsuNetworkCommunications/FSS2-Yang#2]
Hi thank you for adding those capabilities xml files and json files together with them. I still see couple of issues but other then that good job.

1. in module-list-file owner needs to be owner of the repository so in your case it would be FujitsuNetworkCommunications

2. in module-list-file repository needs to be names as your repository so in your case it would be FSS2-Yang.git

if you use these two as I described above then you need to fix path as well it needs to have path from the root of your repository to the xml files for example

`
"path": "FSS2-API-Yang/T100/2.4.2/yang/T100-2.4.2-capabilities.xml"
`

of if you prefer to keep those paths as from yangModels/yang repository then you should be able to do that as well but you need to change owner to yangModels. repository can stay yang.git as it is.

if you have any further questions I am here for you. When you finalize your changes please let me know so I can try it out right away.

**Comment by bennfnc** [comment]
Thanks for providing the feedback. Sure, will make the changes and get them in..

**Comment by miroslavKovacPantheon** [comment]
Hi,

To save you some time I have created a [PR](https://github.com/FujitsuNetworkCommunications/FSS2-Yang/pull/3) for this change. If you would rather go with the another way let me know. 

Thank you
